sudo: required
language: node_js
node_js:
  - 10
dist: trusty
cache: yarn
branches:
  only:
    - master
notifications:
  email: false
  addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - commitlint-travis
  - npm run ci
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/browser
  github_token: $GH_TOKEN
  on:
    branch: master
